name: portfolio
services:
  # nginx:
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - admin

  # frontend:
  #   build:
  #     context: ../portfolio-frontend
  #   image: null

  # admin:
  #   build:
  #     context: ../portfolio-admin
  #   image: null
  #   ports:
  #     - "8000:8000"

  api:
    build:
      context: ../portfolio-api
    ports:
      - "8001:8000"
    env_file:
      - ./services/api/${ENVIRONMENT}.env
    depends_on:
      - postgres

  # cv:
  #   build:
  #     context: ../portfolio-cv
  #   image: null
  #   ports:
  #     - "8002:8000"

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - API_DB_PASSWORD=${API_DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "6543:5432"
    env_file:
      - path: ./services/postgres/secrets.env
        required: false

volumes:
  postgres-data:
